#!/bin/sh
set -e

echo "+ cargo fmt --all -- --check"
cargo fmt --all -- --check

echo "+ cargo clippy --all-targets --all-features -- -D warnings"
cargo clippy --all-targets --all-features -- -D warnings

echo "+ cargo test --workspace --lib"
cargo test --workspace --lib

