use crate::indexes::IndexInfo;
use crate::types::FieldType;
use sqlx::{postgres::PgArguments, Postgres};

// Core trait for migration metadata
// Provides schema information for zero-loss migrations
pub trait OrsxMigrate: Send + Sync {
    fn table_name() -> &'static str;
    fn primary_key_field() -> &'static str;
    fn field_names() -> Vec<&'static str>;
    fn field_types() -> Vec<FieldType>;
    fn field_nullable() -> Vec<bool>;
    fn migration_sql() -> String;
    fn table_indexes() -> Vec<IndexInfo>;

    // Bind field values to SQL query for INSERT operations
    // Generated by proc macro to access struct field values
    fn bind_values_to_query<'q>(
        &'q self,
        query: sqlx::query::Query<'q, Postgres, PgArguments>,
    ) -> sqlx::query::Query<'q, Postgres, PgArguments>;

    // Bind field values for UPDATE statement (non-PK fields first, then PK)
    // Ensures correct parameter order for "SET field1=$1, field2=$2 WHERE pk=$3"
    fn bind_values_for_update<'q>(
        &'q self,
        query: sqlx::query::Query<'q, Postgres, PgArguments>,
    ) -> sqlx::query::Query<'q, Postgres, PgArguments>;

    // Helper method for primary key
    fn primary_key() -> Option<&'static str> {
        let pk = Self::primary_key_field();
        if pk.is_empty() {
            None
        } else {
            Some(pk)
        }
    }

    // Helper method for CREATE TABLE SQL
    fn create_table_sql() -> String {
        Self::migration_sql()
    }
}
