[package]
name = "orsx-macros"
version = "0.0.1"
edition = "2021"
authors = ["TIA Lab"]
description = "Proc macros for orsx"
license = "MIT OR Apache-2.0"
repository = "https://github.com/tia-lab/orsx"

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }
